### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by etrnal70** [PandoraWTG/stupidLMS#2]
# Milestone

Achieve feature-parity with current moodle-based lms

## Student
 - [ ] Login
 - [ ] Enroll to class
 - [ ] Personal Score

## Teacher 
???

## Class
- [ ] Weekly view
- [ ] Upload file (teacher)
- [ ] Create a quiz (teacher)
- [ ] Create an assignment (teacher)
- [ ] Upload work (student)

# Future Ideas

University are rated by LMS activity. So, add more interactivity in the LMS system

- [ ] Piazza-like forum discussion
- [ ] Information API to be used on external chatbot (discord, telegram, etc)
- [ ] How to connect this with siakad ? Need more time to explore

**Comment by Takachii15** [comment]
# Feature suggestion
- Unified repo for _skripsi_ and paper
- Fix mcl problem after uploading task
- previewer for uploaded task
